blank_issues_enabled: false
contact_links:
  - name: DezirClip Website
    url: https://github.com/qiyuanhuakai/dezirclip
    about: Visit the official website for project updates and links.
  - name: Sponsor List
    url: https://github.com/qiyuanhuakai/dezirclip/zh/sponsors.html
    about: View the current sponsor list.
