import type { CSSProperties, ReactNode } from "react";
import type { Locale } from "../../../shared/types";
import type { DefaultAppsMap, InstalledAppOption } from "../../app/types";

export interface LabelWithHintProps {
    readonly label: string;
    readonly hint?: string | ReactNode;
    readonly hintKey: string;
    readonly labelStyle?: CSSProperties;
}

export interface SettingsPanelProps {
    readonly t: (key: string) => string;
    readonly theme: string;
    readonly language: Locale;
    readonly colorMode: string;
    readonly clipboardItemFontSize: number;
    readonly setClipboardItemFontSize: (val: number) => void;
    readonly clipboardTagFontSize: number;
    readonly setClipboardTagFontSize: (val: number) => void;
    readonly fontMain: string;
    readonly setFontMain: (val: string) => void;
    readonly fontMono: string;
    readonly setFontMono: (val: string) => void;
    readonly collapsedGroups: Record<string, boolean>;
    readonly autoStart: boolean;
    readonly silentStart: boolean;
    readonly persistent: boolean;
    readonly persistentLimitEnabled: boolean;
    readonly persistentLimit: number;
    readonly deduplicate: boolean;
    readonly captureFiles: boolean;
    readonly captureRichText: boolean;
    readonly richTextSnapshotPreview: boolean;
    readonly deleteAfterPaste: boolean;
    readonly moveToTopAfterPaste: boolean;
    readonly sequentialMode: boolean;
    readonly sequentialHotkey: string;
    readonly isRecordingSequential: boolean;
    readonly richPasteHotkey: string;
    readonly isRecordingRich: boolean;
    readonly searchHotkey: string;
    readonly isRecordingSearch: boolean;
    readonly privacyProtection: boolean;
    readonly privacyProtectionKinds: string[];
    readonly setPrivacyProtectionKinds: (val: string[]) => void;
    readonly privacyProtectionCustomRules: string;
    readonly setPrivacyProtectionCustomRules: (val: string) => void;
    readonly hotkey: string;
    readonly registryWinVEnabled: boolean;
    readonly setRegistryWinVEnabled: (val: boolean) => void;
    readonly showSearchBox: boolean;
    readonly setShowSearchBox: (val: boolean) => void;
    readonly scrollTopButtonEnabled: boolean;
    readonly setScrollTopButtonEnabled: (val: boolean) => void;
    readonly emojiPanelEnabled: boolean;
    readonly setEmojiPanelEnabled: (val: boolean) => void;
    readonly tagManagerEnabled: boolean;
    readonly setTagManagerEnabled: (val: boolean) => void;
    readonly arrowKeySelection: boolean;
    readonly setArrowKeySelection: (val: boolean) => void;
    readonly soundEnabled: boolean;
    readonly setSoundEnabled: (val: boolean) => void;
    readonly soundVolume: number;
    readonly setSoundVolume: (val: number) => void;
    readonly pasteSoundEnabled: boolean;
    readonly setPasteSoundEnabled: (val: boolean) => void;
    readonly pasteMethod: string;
    readonly setPasteMethod: (val: string) => void;
    readonly hideTrayIcon: boolean;
    readonly setHideTrayIcon: (val: boolean) => void;
    readonly edgeDocking: boolean;
    readonly setEdgeDocking: (val: boolean) => void;
    readonly followMouse: boolean;
    readonly setFollowMouse: (val: boolean) => void;
    readonly disableWebviewGpu: boolean;
    readonly setDisableWebviewGpu: (val: boolean) => void;
    readonly idleDestroyEnabled: boolean;
    readonly setIdleDestroyEnabled: (val: boolean) => void;
    readonly idleDestroySeconds: number;
    readonly setIdleDestroySeconds: (val: number) => void;
    readonly customBackground: string;
    readonly setCustomBackground: (val: string) => void;
    readonly customBackgroundOpacity: number;
    readonly setCustomBackgroundOpacity: (val: number) => void;
    readonly surfaceOpacity: number;
    readonly setSurfaceOpacity: (val: number) => void;
    readonly installedApps: InstalledAppOption[];
    readonly appSettings: Record<string, string>;
    readonly defaultApps: DefaultAppsMap;
    readonly dataPath: string;
    readonly toggleGroup: (group: string) => void;
    readonly setAutoStart: (val: boolean) => void;
    readonly setSilentStart: (val: boolean) => void;
    readonly setPersistent: (val: boolean) => void;
    readonly setPersistentLimitEnabled: (val: boolean) => void;
    readonly setPersistentLimit: (val: number) => void;
    readonly setDeduplicate: (val: boolean) => void;
    readonly setCaptureFiles: (val: boolean) => void;
    readonly setCaptureRichText: (val: boolean) => void;
    readonly setRichTextSnapshotPreview: (val: boolean) => void;
    readonly setDeleteAfterPaste: (val: boolean) => void;
    readonly setMoveToTopAfterPaste: (val: boolean) => void;
    readonly saveAppSetting: (key: string, val: string) => void;
    readonly setSequentialModeState: (val: boolean) => void;
    readonly setIsRecordingSequential: (val: boolean) => void;
    readonly updateSequentialHotkey: (key: string) => void;
    readonly setIsRecordingRich: (val: boolean) => void;
    readonly updateRichPasteHotkey: (key: string) => void;
    readonly setIsRecordingSearch: (val: boolean) => void;
    readonly updateSearchHotkey: (key: string) => void;
    readonly setPrivacyProtection: (val: boolean) => void;
    readonly setIsRecording: (val: boolean) => void;
    readonly isRecording: boolean;
    readonly mainHotkeys: string[];
    readonly updateHotkey: (key: string) => void;
    readonly addMainHotkey: (key: string, options?: { readonly skipAvailabilityCheck?: boolean }) => Promise<boolean>;
    readonly removeMainHotkey: (key: string) => Promise<boolean>;
    readonly setTheme: (val: string) => void;
    readonly setColorMode: (val: string) => void;
    readonly setLanguage: (val: Locale) => void;
    readonly showAppBorder: boolean;
    readonly setShowAppBorder: (val: boolean) => void;
    readonly compactMode: boolean;
    readonly setCompactMode: (val: boolean) => void;
    readonly checkHotkeyConflict: (newHotkey: string, mode: "main" | "sequential" | "rich" | "search") => boolean;
    readonly handleResetSettings: () => void;
}
